version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "urlshorter-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hfecv3sejgsr"
s3_prefix = "urlshorter"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

